language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
os:
    - os-x
    - linux
    - windows
# command to connect os
install:
  - pip install pytz
  - pip install pytest
  - pip install .
# command to run tests
script:
  - pytest